"""modelo inicial

Revision ID: 518fb670507d
Revises: 
Create Date: 2026-09-11 10:42:44.817362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518fb670507d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_encomenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('cor_badge', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipos_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('encomendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_produto_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('detalhes_personalizacao', sa.Text(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_entrega_prevista', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_sinal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status_encomenda.id'], ),
    sa.ForeignKeyConstraint(['tipo_produto_id'], ['tipos_produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encomendas_cliente_id'), 'encomendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_encomendas_data_entrega_prevista'), 'encomendas', ['data_entrega_prevista'], unique=False)
    op.create_index(op.f('ix_encomendas_status_id'), 'encomendas', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encomendas_status_id'), table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_data_entrega_prevista'), table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_cliente_id'), table_name='encomendas')
    op.drop_table('encomendas')
    op.drop_table('tipos_produto')
    op.drop_table('status_encomenda')
    op.drop_table('clientes')
    # ### end Alembic commands ###
